{% set version = "16.13.0" %}

package:
  name: path
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/path/path-{{ version }}.tar.gz
  sha256: eff5b136eac2f9151e671458a1c396ca34d5c9e0c344c2ba915d9d1454dbec8d

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python

test:
  imports:
    - path

about:
  home: https://github.com/jaraco/path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A module wrapper for os.path
  description: |
    path implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://path.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jaraco/path/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path

extra:
  recipe-maintainers:
    - nehaljwani
